spring.application.name=resource-management

spring.datasource.url=jdbc:postgresql://localhost:5432/resource_management
spring.datasource.username=postgres
spring.datasource.password=nikil

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080